Repository AsYetUntitled/Framework, pull requests merged in 2018-06, with the labels that each got.

#436 Updated for tanks DLC
  Altis_Life.Altis/SpyGlass/fn_initSpy.sqf
  Altis_Life.Altis/SpyGlass/fn_notifyAdmins.sqf
  Altis_Life.Altis/config/Config_SpyGlass.hpp
  BEFilters/scripts.txt
Labels: In Progress, bug-fix, duplicate

#455 Lightpoints
  Altis_Life.Altis/core/cop/fn_copLights.sqf
  Altis_Life.Altis/core/medical/fn_medicLights.sqf
Labels: enhancement

#438 Update TON_fnc_index
  life_server/functions.sqf
Labels: In Progress, enhancement

#457 Corrected misleading reference to lines
  Altis_Life.Altis/config/Config_Master.hpp
Labels: enhancement
