Repository AsYetUntitled/Framework, pull requests merged in 2019-12, with the labels that each got.

#594 Headgear config for startLoadout
  Altis_Life.Altis/config/Config_Loadouts.hpp
  Altis_Life.Altis/core/functions/fn_startLoadout.sqf
Labels: 6.0.0, enhancement

#595 Anti-dupe improvement & esc menu handler
  Altis_Life.Altis/Functions.hpp
  Altis_Life.Altis/config/Config_SpyGlass.hpp
  Altis_Life.Altis/core/fn_setupEVH.sqf
  Altis_Life.Altis/core/functions/fn_escInterupt.sqf
  Altis_Life.Altis/core/functions/fn_inventoryOpened.sqf
  Altis_Life.Altis/core/functions/fn_onGameInterrupt.sqf
  Altis_Life.Altis/core/init.sqf
Labels: 6.0.0, bug-fix, enhancement

#597 Gang disband fix
  Altis_Life.Altis/core/gangs/fn_gangDisbanded.sqf
  life_hc/MySQL/Gangs/fn_removeGang.sqf
  life_server/Functions/Gangs/fn_removeGang.sqf
Labels: 5.0.0, bug-fix
